# Use the official PSQL image
FROM postgres:12-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_PASSWORD=ieeecs@usf|is|amazing
ENV POSTGRES_DB=workshopdb
ENV POSTGRES_USER=akmalchik

# Expose the PostgreSQL port
EXPOSE 5432
